/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_pstar (void);
GtkWidget* create_camera_control (void);
GtkWidget* create_wcs_edit (void);
GtkWidget* create_show_text (void);
GtkWidget* create_create_recipy (void);
GtkWidget* create_yes_no (void);
GtkWidget* create_phot_run (void);
GtkWidget* create_image_processing (void);
GtkWidget* create_obscript_stopped (void);
GtkWidget* create_par_edit (void);
GtkWidget* create_entry_prompt (void);
GtkWidget* create_guide_window (void);
GtkWidget* create_mband_dialog (void);
